# Generated by Django 4.2.5 on 2023-12-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
